2025-06-18 17:35:54,130 INFO Watching for file changes with StatReloader
2025-06-18 17:35:56,333 INFO Request: GET / | User: 
2025-06-18 17:35:56,335 WARNING Not Found: /
2025-06-18 17:35:56,429 INFO Request: GET /favicon.ico | User: 
2025-06-18 17:35:56,430 WARNING Not Found: /favicon.ico
2025-06-18 17:35:58,709 INFO Request: GET /admin/ | User: 
2025-06-18 17:35:58,862 INFO Request: GET /admin/login/ | User: 
2025-06-18 17:36:00,779 INFO Request: GET /event/ | User: 
2025-06-18 17:36:37,271 INFO Request: GET /event/ | User: 
2025-06-18 17:36:37,343 INFO Request: GET /favicon.ico | User: 
2025-06-18 17:36:37,343 WARNING Not Found: /favicon.ico
2025-06-18 17:36:43,187 INFO D:\python\university_backend\university_backend\urls.py changed, reloading.
2025-06-18 17:36:43,914 INFO Watching for file changes with StatReloader
2025-06-18 17:36:44,973 INFO Request: GET /event/ | User: 
2025-06-18 17:36:45,028 INFO Request: GET /favicon.ico | User: 
2025-06-18 17:36:45,030 WARNING Not Found: /favicon.ico
2025-06-18 17:36:45,519 INFO Request: GET /event/ | User: 
2025-06-18 17:36:45,933 INFO Request: GET /event/ | User: 
2025-06-18 17:36:46,246 INFO Request: GET /event/ | User: 
2025-06-18 17:36:46,449 INFO Request: GET /event/ | User: 
2025-06-18 17:36:54,016 INFO Watching for file changes with StatReloader
2025-06-18 17:36:56,281 INFO Request: GET / | User: 
2025-06-18 17:36:56,282 WARNING Not Found: /
2025-06-18 17:37:24,883 INFO D:\python\university_backend\university_backend\settings.py changed, reloading.
2025-06-18 17:37:25,516 INFO Watching for file changes with StatReloader
2025-06-18 17:37:29,449 INFO Watching for file changes with StatReloader
2025-06-18 17:37:31,232 INFO Request: GET / | User: 
2025-06-18 17:37:31,248 WARNING Not Found: /
2025-06-18 17:37:34,658 INFO Request: GET /admin/ | User: 
2025-06-18 17:37:34,691 INFO Request: GET /admin/login/ | User: 
2025-06-18 17:37:37,248 INFO Request: GET /event/ | User: 
2025-06-18 17:37:38,598 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:37:49,613 INFO Request: POST /api/token/ | User: 
2025-06-18 17:37:49,624 WARNING Unauthorized: /api/token/
2025-06-18 17:37:54,721 INFO Request: POST /api/token/ | User: 
2025-06-18 17:37:54,729 WARNING Unauthorized: /api/token/
2025-06-18 17:38:22,740 INFO Request: POST /api/token/ | User: 
2025-06-18 17:39:32,233 INFO Request: GET /group/ | User: root
2025-06-18 17:40:10,122 INFO Request: POST /group/ | User: root
2025-06-18 17:40:22,435 INFO Request: POST /register/ | User: 
2025-06-18 17:40:22,446 WARNING Unauthorized: /register/
2025-06-18 17:40:27,275 INFO Request: POST /register/ | User: 
2025-06-18 17:40:27,284 WARNING Bad Request: /register/
2025-06-18 17:41:38,200 INFO Request: POST /register/ | User: 
2025-06-18 17:41:38,208 WARNING Bad Request: /register/
2025-06-18 17:41:47,597 INFO Request: POST /register/ | User: 
2025-06-18 17:42:26,737 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\usercontrol_api\views.py", line 30, in post
    if serializer.is_valid():
       ~~~~~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "D:\python\university_backend\usercontrol_api\serializers.py", line 20, in validate
    attrs['email'] = f"{attrs['username']}#{attrs['id']}@‚„ÚÛ_university.edu"
                                            ~~~~~^^^^^^
KeyError: 'id'
2025-06-18 17:42:26,742 INFO Request: POST /register/ | User: 
2025-06-18 17:43:22,473 INFO D:\python\university_backend\usercontrol_api\serializers.py changed, reloading.
2025-06-18 17:43:23,087 INFO Watching for file changes with StatReloader
2025-06-18 17:43:35,883 INFO D:\python\university_backend\usercontrol_api\serializers.py changed, reloading.
2025-06-18 17:43:36,601 INFO Watching for file changes with StatReloader
2025-06-18 17:43:38,789 INFO Request: POST /register/ | User: 
2025-06-18 17:44:33,141 INFO Request: PATCH /group/1/ | User: root
2025-06-18 17:44:50,974 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
    ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\event_api\serializers.py", line 63, in create
    event = Event.objects.create(**validated_data)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 661, in create
    obj = self.model(**kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\base.py", line 569, in __init__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Event() got unexpected keyword arguments: 'action'
2025-06-18 17:44:50,977 INFO Request: POST /event/ | User: root
2025-06-18 17:44:57,598 INFO Request: POST /event/ | User: root
2025-06-18 17:45:48,863 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:45:49,630 INFO Watching for file changes with StatReloader
2025-06-18 17:45:51,544 INFO Request: POST /event/ | User: root
2025-06-18 17:45:51,564 WARNING Bad Request: /event/
2025-06-18 17:46:00,393 INFO Request: POST /event/ | User: root
2025-06-18 17:46:00,403 WARNING Bad Request: /event/
2025-06-18 17:46:10,134 INFO Request: POST /event/ | User: root
2025-06-18 17:46:10,145 WARNING Bad Request: /event/
2025-06-18 17:46:30,973 INFO Request: POST /event/ | User: root
2025-06-18 17:46:30,983 WARNING Bad Request: /event/
2025-06-18 17:46:33,174 INFO Request: POST /event/ | User: root
2025-06-18 17:46:33,183 WARNING Bad Request: /event/
2025-06-18 17:47:29,588 INFO Request: POST /event/ | User: root
2025-06-18 17:47:29,597 WARNING Bad Request: /event/
2025-06-18 17:47:33,831 INFO Request: POST /event/ | User: root
2025-06-18 17:47:33,841 WARNING Bad Request: /event/
2025-06-18 17:47:42,266 INFO Request: POST /event/ | User: root
2025-06-18 17:47:42,277 WARNING Bad Request: /event/
2025-06-18 17:47:47,181 INFO Request: POST /event/ | User: root
2025-06-18 17:47:47,193 WARNING Bad Request: /event/
2025-06-18 17:48:08,016 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:48:08,899 INFO Watching for file changes with StatReloader
2025-06-18 17:48:17,676 INFO Request: GET /group/1/ | User: root
2025-06-18 17:48:24,771 INFO Request: POST /event/ | User: root
2025-06-18 17:48:35,985 INFO Request: DELETE /event/2. | User: 
2025-06-18 17:48:36,024 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:48:38,076 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_arfpfgC.jpg
2025-06-18 17:48:38,077 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_ZWekseM.jpg
2025-06-18 17:48:38,079 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_OxVU7vE.webm
2025-06-18 17:48:38,085 INFO Request: DELETE /event/2/ | User: root
2025-06-18 17:48:38,142 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:48:47,866 INFO Request: DELETE /event/2/ | User: root
2025-06-18 17:48:47,885 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:49:27,909 INFO Request: DELETE /event/2/ | User: root
2025-06-18 17:49:27,928 WARNING Not Found: /event/2/
2025-06-18 17:49:33,796 INFO Request: GET /event/2/ | User: root
2025-06-18 17:49:33,818 WARNING Not Found: /event/2/
2025-06-18 17:49:36,037 INFO Request: GET /event/ | User: root
2025-06-18 17:49:44,074 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-18 17:49:44,075 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-18 17:49:44,077 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-18 17:49:44,082 INFO Request: DELETE /event/1/ | User: root
2025-06-18 17:49:52,641 INFO Request: POST /event/ | User: root
2025-06-18 17:49:59,103 INFO Request: POST /event/ | User: root
2025-06-18 17:51:11,157 INFO Request: GET /event/4/ | User: root
2025-06-18 17:51:11,194 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:51:22,219 INFO Request: GET /event/ | User: 
2025-06-18 17:51:23,658 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:52:00,908 INFO Request: GET /group/ | User: 
2025-06-18 17:52:07,995 INFO Request: GET /group/1/ | User: 
2025-06-18 17:52:09,827 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:52:13,579 INFO Request: POST /__debug__/sql_select/ | User: 
2025-06-18 17:52:20,020 INFO Request: GET /event/ | User: 
2025-06-18 17:52:52,464 INFO D:\python\university_backend\university_backend\settings.py changed, reloading.
2025-06-18 17:52:53,135 INFO Watching for file changes with StatReloader
2025-06-18 17:52:54,563 INFO Request: GET /event/4/ | User: root
2025-06-18 17:52:58,714 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_VJQ7Zap.jpg
2025-06-18 17:52:58,715 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_S1XV1Qn.jpg
2025-06-18 17:52:58,716 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_DURSryt.webm
2025-06-18 17:52:58,719 INFO Request: DELETE /event/4/ | User: root
2025-06-18 17:53:07,603 INFO Request: GET /event/ | User: 
2025-06-18 17:53:09,179 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:53:28,108 INFO Request: GET /event/3/ | User: 
2025-06-18 17:53:52,064 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:54:05,476 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:57:49,989 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:57:50,652 INFO Watching for file changes with StatReloader
2025-06-18 17:58:02,294 ERROR Internal Server Error: /event/3/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'group_id' was declared on serializer EventSerializer, but has not been included in the 'fields' option.
2025-06-18 17:58:02,298 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:58:14,919 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:58:15,643 INFO Watching for file changes with StatReloader
2025-06-18 17:58:17,186 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:58:17,219 WARNING Bad Request: /event/3/
2025-06-18 17:58:23,428 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:58:36,337 INFO Request: POST /event/ | User: root
2025-06-18 17:59:16,349 INFO Watching for file changes with StatReloader
2025-06-18 17:59:18,782 INFO Request: GET /event/ | User: root
2025-06-18 17:59:24,053 INFO Request: GET /event/5/ | User: root
2025-06-18 17:59:26,973 INFO Request: GET /event/ | User: root
2025-06-18 18:00:47,746 INFO Watching for file changes with StatReloader
2025-06-18 18:00:49,854 INFO Request: POST /event/ | User: root
2025-06-18 18:18:23,771 INFO Watching for file changes with StatReloader
2025-06-18 18:18:26,480 INFO Request: POST /event/ | User: root
2025-06-18 18:18:30,103 INFO Request: GET /event/ | User: root
2025-06-18 18:19:52,485 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:19:53,502 INFO Watching for file changes with StatReloader
2025-06-18 18:20:43,566 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:20:44,197 INFO Watching for file changes with StatReloader
2025-06-18 18:21:18,921 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:21:19,537 INFO Watching for file changes with StatReloader
2025-06-18 18:21:38,687 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:21:39,363 INFO Watching for file changes with StatReloader
2025-06-18 18:22:32,542 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:22:33,132 INFO Watching for file changes with StatReloader
2025-06-18 18:22:45,150 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:22:45,795 INFO Watching for file changes with StatReloader
2025-06-18 18:22:49,540 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:22:50,154 INFO Watching for file changes with StatReloader
2025-06-18 18:24:23,978 INFO Watching for file changes with StatReloader
2025-06-18 18:24:25,989 INFO Request: GET / | User: 
2025-06-18 18:24:26,006 WARNING Not Found: /
2025-06-18 18:24:26,899 INFO Request: GET /admin/ | User: 
2025-06-18 18:24:26,950 INFO Request: GET /admin/login/ | User: 
2025-06-18 18:24:37,288 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:24:38,211 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:24:38,215 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:24:38,460 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:24:38,462 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:24:38,763 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:25:16,147 INFO Watching for file changes with StatReloader
2025-06-18 18:25:18,870 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:25:19,112 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:25:19,115 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:25:19,274 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:25:19,276 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:25:19,519 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:26:03,102 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:26:03,783 INFO Watching for file changes with StatReloader
2025-06-18 18:26:04,424 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:26:04,660 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:26:04,663 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:26:04,835 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:26:04,836 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:26:05,076 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:26:18,782 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:26:19,460 INFO Watching for file changes with StatReloader
2025-06-18 18:28:28,030 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:28:28,841 INFO Watching for file changes with StatReloader
2025-06-18 18:28:29,620 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:28:29,707 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:28:56,192 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:28:56,871 INFO Watching for file changes with StatReloader
2025-06-18 18:28:57,465 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:28:57,660 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type type is not JSON serializable
2025-06-18 18:28:57,662 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:28:57,817 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type type is not JSON serializable
2025-06-18 18:28:57,818 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:28:58,057 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:06,743 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:07,468 INFO Watching for file changes with StatReloader
2025-06-18 18:29:08,448 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:08,641 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:08,644 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:08,801 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:08,802 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:09,037 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:09,448 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:09,615 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:09,616 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:09,770 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:09,772 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:10,010 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:29,715 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:30,454 INFO Watching for file changes with StatReloader
2025-06-18 18:29:31,192 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:31,383 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:31,386 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:31,544 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:31,546 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:31,781 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:41,353 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:41,998 INFO Watching for file changes with StatReloader
2025-06-18 18:29:42,575 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:42,770 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:42,772 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:42,926 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:42,928 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:43,170 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:52,632 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:52,807 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:52,808 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:52,971 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:52,973 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:53,013 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:53,716 INFO Watching for file changes with StatReloader
2025-06-18 18:29:54,399 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:54,415 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:54,484 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:30:06,689 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:30:07,408 INFO Watching for file changes with StatReloader
2025-06-18 18:30:36,935 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:30:37,592 INFO Watching for file changes with StatReloader
2025-06-18 18:31:59,296 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:31:59,941 INFO Watching for file changes with StatReloader
2025-06-18 18:32:00,817 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:32:01,076 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:32:01,078 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:32:01,237 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:32:01,238 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:32:01,488 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:32:12,886 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:32:13,682 INFO Watching for file changes with StatReloader
2025-06-18 18:32:14,387 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:32:14,470 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:32:42,139 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:32:42,858 INFO Watching for file changes with StatReloader
2025-06-18 18:32:43,530 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:32:43,617 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:33:23,647 INFO Watching for file changes with StatReloader
2025-06-18 18:33:26,553 INFO Request: GET / | User: 
2025-06-18 18:33:26,571 WARNING Not Found: /
2025-06-18 18:33:27,393 INFO Request: GET /admin/ | User: 
2025-06-18 18:33:27,430 INFO Request: GET /admin/login/ | User: 
2025-06-18 18:33:28,056 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:33:28,252 INFO Request: GET /api/schema/ | User: 
2025-06-19 12:05:44,778 INFO Watching for file changes with StatReloader
2025-06-19 12:08:58,908 INFO Request: POST /api/token/ | User: 
2025-06-19 12:09:07,668 INFO Request: GET /event/ | User: root
2025-06-19 12:09:15,938 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:00,611 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 12:10:01,339 INFO Watching for file changes with StatReloader
2025-06-19 12:10:03,139 ERROR Internal Server Error: /event/7/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "D:\python\university_backend\event_api\views.py", line 148, in get_object
    return Event.objects.get(pk=self.kwargs['pk']).prefetch_related('photos', 'videos').select_related('author')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Event' object has no attribute 'prefetch_related'
2025-06-19 12:10:03,142 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:24,940 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 12:10:25,620 INFO Watching for file changes with StatReloader
2025-06-19 12:10:27,072 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:39,058 INFO Request: GET /event/7 | User: 
2025-06-19 12:10:39,260 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:47,071 INFO Request: GET /event/ | User: root
2025-06-19 12:12:42,636 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 12:12:43,362 INFO Watching for file changes with StatReloader
2025-06-19 12:12:48,263 INFO Request: GET /event/7. | User: 
2025-06-19 12:12:48,298 WARNING Not Found: /event/7.
2025-06-19 12:12:49,399 INFO Request: GET /event/7/ | User: root
2025-06-19 12:13:02,937 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 12:13:03,633 INFO Watching for file changes with StatReloader
2025-06-19 12:13:05,027 INFO Request: GET /event/7/ | User: root
2025-06-19 14:11:16,668 INFO Watching for file changes with StatReloader
2025-06-19 14:11:26,365 INFO Request: GET /event/7/ | User: 
2025-06-19 14:11:26,396 WARNING Unauthorized: /event/7/
2025-06-19 14:11:34,739 INFO Request: POST /api/token/ | User: 
2025-06-19 14:11:42,650 INFO Request: GET /event/7/ | User: root
2025-06-19 14:11:47,677 INFO Request: GET /event/ | User: root
2025-06-19 14:11:59,885 INFO Request: POST /event/ | User: root
2025-06-19 14:12:19,718 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:12:20,491 INFO Watching for file changes with StatReloader
2025-06-19 14:15:27,694 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 14:15:29,176 INFO Watching for file changes with StatReloader
2025-06-19 14:16:12,333 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 14:16:13,087 INFO Watching for file changes with StatReloader
2025-06-19 14:16:29,254 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:16:30,048 INFO Watching for file changes with StatReloader
2025-06-19 14:16:32,158 INFO Request: GET /event/ | User: root
2025-06-19 14:16:46,048 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-19 14:16:46,049 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-19 14:16:46,053 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:16:46,058 INFO Request: DELETE /event/3/ | User: root
2025-06-19 14:16:49,560 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_ZH3mhoq.jpg
2025-06-19 14:16:49,561 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_tvXZpbf.jpg
2025-06-19 14:16:49,565 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_bfQreOa.webm
2025-06-19 14:16:49,570 INFO Request: DELETE /event/5/ | User: root
2025-06-19 14:16:52,096 ERROR Internal Server Error: /event/5/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "D:\python\university_backend\event_api\views.py", line 148, in get_object
    return Event.objects.get(pk=self.kwargs['pk'])
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
event_api.models.Event.DoesNotExist: Event matching query does not exist.
2025-06-19 14:16:52,100 INFO Request: GET /event/5/ | User: root
2025-06-19 14:17:02,383 INFO Request: GET /event/ | User: root
2025-06-19 14:17:16,574 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_E9GWBde.jpg
2025-06-19 14:17:16,575 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_9iCjBni.jpg
2025-06-19 14:17:16,577 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_YqArH0A.webm
2025-06-19 14:17:16,581 INFO Request: DELETE /event/6/ | User: root
2025-06-19 14:17:19,384 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_ykiOwa9.jpg
2025-06-19 14:17:19,384 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_vTNCIWl.jpg
2025-06-19 14:17:19,387 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_VHGtW1Y.webm
2025-06-19 14:17:19,390 INFO Request: DELETE /event/7/ | User: root
2025-06-19 14:17:22,232 INFO Request: GET /event/ | User: root
2025-06-19 14:17:25,745 INFO Request: GET /event/8/ | User: root
2025-06-19 14:17:48,583 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:17:49,351 INFO Watching for file changes with StatReloader
2025-06-19 14:17:50,932 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'author' was declared on serializer ListEventSerializer, but has not been included in the 'fields' option.
2025-06-19 14:17:50,936 INFO Request: GET /event/ | User: root
2025-06-19 14:18:16,022 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:18:16,671 INFO Watching for file changes with StatReloader
2025-06-19 14:18:18,002 INFO Request: GET /event/ | User: root
2025-06-19 14:19:01,657 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:19:02,958 INFO Watching for file changes with StatReloader
2025-06-19 14:19:04,418 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'first_photo' was declared on serializer ListEventSerializer, but has not been included in the 'fields' option.
2025-06-19 14:19:04,420 INFO Request: GET /event/ | User: root
2025-06-19 14:19:29,520 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:19:30,251 INFO Watching for file changes with StatReloader
2025-06-19 14:19:31,752 INFO Request: GET /event/ | User: root
2025-06-19 14:20:18,375 INFO Request: GET /event/ | User: root
2025-06-19 14:20:40,439 INFO Request: GET /event/ | User: root
2025-06-19 14:20:51,364 INFO Request: GET /event/ | User: root
2025-06-19 14:21:09,538 INFO Request: GET /event/8. | User: 
2025-06-19 14:21:09,566 WARNING Not Found: /event/8.
2025-06-19 14:21:11,050 INFO Request: GET /event/8/ | User: root
2025-06-19 14:21:48,657 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:21:49,546 INFO Watching for file changes with StatReloader
2025-06-19 14:21:50,746 INFO Request: GET /event/8/ | User: root
2025-06-19 14:22:30,531 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:22:31,294 INFO Watching for file changes with StatReloader
2025-06-19 14:22:32,568 INFO Request: GET /event/ | User: root
2025-06-19 14:24:59,319 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:25:00,463 INFO Watching for file changes with StatReloader
2025-06-19 14:25:04,469 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 375, in fields
    fields[key] = value
    ~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 167, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\fields.py", line 358, in bind
    assert self.source != field_name, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: It is redundant to specify `source='group'` on field 'PrimaryKeyRelatedField' in serializer 'EventSerializer', because it is the same as the field name. Remove the `source` keyword argument.
2025-06-19 14:25:04,472 INFO Request: POST /event/ | User: root
2025-06-19 14:25:23,504 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:25:24,251 INFO Watching for file changes with StatReloader
2025-06-19 14:25:31,069 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:25:31,763 INFO Watching for file changes with StatReloader
2025-06-19 14:25:32,719 INFO Request: POST /event/ | User: root
2025-06-19 14:26:00,327 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:26:01,056 INFO Watching for file changes with StatReloader
2025-06-19 14:26:02,239 INFO Request: POST /event/ | User: root
2025-06-19 14:26:11,769 INFO Request: GET /event/ | User: root
2025-06-19 14:26:32,110 INFO Request: GET /event/ | User: root
2025-06-19 14:26:44,644 INFO Request: GET /admin/ | User: 
2025-06-19 14:26:44,813 INFO Request: GET /admin/login/ | User: 
2025-06-19 14:26:44,963 INFO Request: GET /favicon.ico | User: 
2025-06-19 14:26:44,978 WARNING Not Found: /favicon.ico
2025-06-19 14:26:46,900 INFO Request: POST /admin/login/ | User: root
2025-06-19 14:26:47,149 INFO Request: GET /admin/ | User: root
2025-06-19 14:26:49,492 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:26:49,650 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:26:53,035 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:26:54,011 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_voo1bvf.jpg
2025-06-19 14:26:54,012 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_tFEiHkL.webm
2025-06-19 14:26:54,014 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-19 14:26:54,014 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-19 14:26:54,016 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:26:54,017 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_gItzWUQ.jpg
2025-06-19 14:26:54,017 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_rEo7gSN.jpg
2025-06-19 14:26:54,019 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_4m2ZX2y.webm
2025-06-19 14:26:54,022 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:26:54,142 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:26:54,225 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:27:09,411 INFO Request: GET /event/ | User: root
2025-06-19 14:27:50,849 INFO Request: POST /event/ | User: root
2025-06-19 14:27:50,862 WARNING Bad Request: /event/
2025-06-19 14:28:00,107 INFO Request: POST /event/ | User: root
2025-06-19 14:28:13,518 INFO Request: GET /event/ | User: root
2025-06-19 14:28:25,479 INFO Request: GET /event/11/ | User: root
2025-06-19 14:29:04,247 INFO Request: PATCH /event/11/ | User: root
2025-06-19 14:29:09,962 INFO Request: GET /event/11/ | User: root
2025-06-19 14:29:27,403 INFO Request: GET /event/11/ | User: root
2025-06-19 14:29:37,908 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-19 14:29:37,908 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-19 14:29:37,908 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_qUjpdDs.jpg
2025-06-19 14:29:37,909 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_1CwMmnS.jpg
2025-06-19 14:29:37,912 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:29:37,916 INFO Request: DELETE /event/11/ | User: root
2025-06-19 14:29:57,516 INFO Request: POST /event/ | User: root
2025-06-19 14:29:57,523 WARNING Bad Request: /event/
2025-06-19 14:30:01,997 INFO Request: POST /event/ | User: root
2025-06-19 14:30:12,505 INFO Request: GET /event/ | User: root
2025-06-19 14:30:30,008 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:30:30,723 INFO Watching for file changes with StatReloader
2025-06-19 14:30:32,166 INFO Request: POST /event/ | User: root
2025-06-19 14:30:35,991 INFO Request: GET /event/ | User: root
2025-06-19 14:30:41,443 INFO Request: GET /event/13/ | User: root
2025-06-19 14:30:55,483 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_gOl1fVX.jpg
2025-06-19 14:30:55,484 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_kri3vcf.jpg
2025-06-19 14:30:55,487 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_PyqW8fl.webm
2025-06-19 14:30:55,492 INFO Request: DELETE /event/13/ | User: root
2025-06-19 14:31:03,358 INFO Request: GET /event/12/ | User: root
2025-06-19 14:31:12,052 INFO Request: PATCH /event/12/ | User: root
2025-06-19 14:31:15,835 INFO Request: GET /event/12/ | User: root
2025-06-19 14:31:31,936 INFO Request: PATCH /event/12/ | User: root
2025-06-19 14:31:33,949 INFO Request: GET /event/12/ | User: root
2025-06-19 14:31:55,016 INFO Request: POST /event/ | User: root
2025-06-19 14:31:55,025 WARNING Bad Request: /event/
2025-06-19 14:32:19,623 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:32:20,306 INFO Watching for file changes with StatReloader
2025-06-19 14:32:24,772 INFO Request: POST /event/ | User: root
2025-06-19 14:32:30,288 INFO Request: GET /event/14/ | User: root
2025-06-19 14:33:07,560 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 14:33:08,219 INFO Watching for file changes with StatReloader
2025-06-19 14:33:18,490 INFO Request: GET /event/14/ | User: root
2025-06-19 14:33:22,204 INFO Request: POST /event/ | User: root
2025-06-19 14:33:22,217 WARNING Bad Request: /event/
2025-06-19 14:36:49,343 INFO Watching for file changes with StatReloader
2025-06-19 14:36:51,392 INFO Request: GET / | User: root
2025-06-19 14:36:51,419 WARNING Not Found: /
2025-06-19 14:36:55,063 INFO Request: GET /admin/ | User: root
2025-06-19 14:36:58,304 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:36:58,425 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:01,631 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:37:03,313 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:37:03,317 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:37:03,549 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:37:03,633 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:05,164 INFO Request: GET /admin/event_api/event/add/ | User: root
2025-06-19 14:37:05,269 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:15,578 INFO Request: GET /admin/event_api/event/add/ | User: root
2025-06-19 14:37:15,721 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:15,863 INFO Request: GET /favicon.ico | User: root
2025-06-19 14:37:15,895 WARNING Not Found: /favicon.ico
2025-06-19 14:37:32,396 INFO Request: POST /event/ | User: root
2025-06-19 14:37:32,405 WARNING Bad Request: /event/
2025-06-19 14:37:38,888 INFO Request: POST /event/ | User: root
