2025-06-18 17:35:54,130 INFO Watching for file changes with StatReloader
2025-06-18 17:35:56,333 INFO Request: GET / | User: 
2025-06-18 17:35:56,335 WARNING Not Found: /
2025-06-18 17:35:56,429 INFO Request: GET /favicon.ico | User: 
2025-06-18 17:35:56,430 WARNING Not Found: /favicon.ico
2025-06-18 17:35:58,709 INFO Request: GET /admin/ | User: 
2025-06-18 17:35:58,862 INFO Request: GET /admin/login/ | User: 
2025-06-18 17:36:00,779 INFO Request: GET /event/ | User: 
2025-06-18 17:36:37,271 INFO Request: GET /event/ | User: 
2025-06-18 17:36:37,343 INFO Request: GET /favicon.ico | User: 
2025-06-18 17:36:37,343 WARNING Not Found: /favicon.ico
2025-06-18 17:36:43,187 INFO D:\python\university_backend\university_backend\urls.py changed, reloading.
2025-06-18 17:36:43,914 INFO Watching for file changes with StatReloader
2025-06-18 17:36:44,973 INFO Request: GET /event/ | User: 
2025-06-18 17:36:45,028 INFO Request: GET /favicon.ico | User: 
2025-06-18 17:36:45,030 WARNING Not Found: /favicon.ico
2025-06-18 17:36:45,519 INFO Request: GET /event/ | User: 
2025-06-18 17:36:45,933 INFO Request: GET /event/ | User: 
2025-06-18 17:36:46,246 INFO Request: GET /event/ | User: 
2025-06-18 17:36:46,449 INFO Request: GET /event/ | User: 
2025-06-18 17:36:54,016 INFO Watching for file changes with StatReloader
2025-06-18 17:36:56,281 INFO Request: GET / | User: 
2025-06-18 17:36:56,282 WARNING Not Found: /
2025-06-18 17:37:24,883 INFO D:\python\university_backend\university_backend\settings.py changed, reloading.
2025-06-18 17:37:25,516 INFO Watching for file changes with StatReloader
2025-06-18 17:37:29,449 INFO Watching for file changes with StatReloader
2025-06-18 17:37:31,232 INFO Request: GET / | User: 
2025-06-18 17:37:31,248 WARNING Not Found: /
2025-06-18 17:37:34,658 INFO Request: GET /admin/ | User: 
2025-06-18 17:37:34,691 INFO Request: GET /admin/login/ | User: 
2025-06-18 17:37:37,248 INFO Request: GET /event/ | User: 
2025-06-18 17:37:38,598 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:37:49,613 INFO Request: POST /api/token/ | User: 
2025-06-18 17:37:49,624 WARNING Unauthorized: /api/token/
2025-06-18 17:37:54,721 INFO Request: POST /api/token/ | User: 
2025-06-18 17:37:54,729 WARNING Unauthorized: /api/token/
2025-06-18 17:38:22,740 INFO Request: POST /api/token/ | User: 
2025-06-18 17:39:32,233 INFO Request: GET /group/ | User: root
2025-06-18 17:40:10,122 INFO Request: POST /group/ | User: root
2025-06-18 17:40:22,435 INFO Request: POST /register/ | User: 
2025-06-18 17:40:22,446 WARNING Unauthorized: /register/
2025-06-18 17:40:27,275 INFO Request: POST /register/ | User: 
2025-06-18 17:40:27,284 WARNING Bad Request: /register/
2025-06-18 17:41:38,200 INFO Request: POST /register/ | User: 
2025-06-18 17:41:38,208 WARNING Bad Request: /register/
2025-06-18 17:41:47,597 INFO Request: POST /register/ | User: 
2025-06-18 17:42:26,737 ERROR Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\usercontrol_api\views.py", line 30, in post
    if serializer.is_valid():
       ~~~~~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "D:\python\university_backend\usercontrol_api\serializers.py", line 20, in validate
    attrs['email'] = f"{attrs['username']}#{attrs['id']}@‚„ÚÛ_university.edu"
                                            ~~~~~^^^^^^
KeyError: 'id'
2025-06-18 17:42:26,742 INFO Request: POST /register/ | User: 
2025-06-18 17:43:22,473 INFO D:\python\university_backend\usercontrol_api\serializers.py changed, reloading.
2025-06-18 17:43:23,087 INFO Watching for file changes with StatReloader
2025-06-18 17:43:35,883 INFO D:\python\university_backend\usercontrol_api\serializers.py changed, reloading.
2025-06-18 17:43:36,601 INFO Watching for file changes with StatReloader
2025-06-18 17:43:38,789 INFO Request: POST /register/ | User: 
2025-06-18 17:44:33,141 INFO Request: PATCH /group/1/ | User: root
2025-06-18 17:44:50,974 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
    ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\event_api\serializers.py", line 63, in create
    event = Event.objects.create(**validated_data)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 661, in create
    obj = self.model(**kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\base.py", line 569, in __init__
    raise TypeError(
    ...<2 lines>...
    )
TypeError: Event() got unexpected keyword arguments: 'action'
2025-06-18 17:44:50,977 INFO Request: POST /event/ | User: root
2025-06-18 17:44:57,598 INFO Request: POST /event/ | User: root
2025-06-18 17:45:48,863 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:45:49,630 INFO Watching for file changes with StatReloader
2025-06-18 17:45:51,544 INFO Request: POST /event/ | User: root
2025-06-18 17:45:51,564 WARNING Bad Request: /event/
2025-06-18 17:46:00,393 INFO Request: POST /event/ | User: root
2025-06-18 17:46:00,403 WARNING Bad Request: /event/
2025-06-18 17:46:10,134 INFO Request: POST /event/ | User: root
2025-06-18 17:46:10,145 WARNING Bad Request: /event/
2025-06-18 17:46:30,973 INFO Request: POST /event/ | User: root
2025-06-18 17:46:30,983 WARNING Bad Request: /event/
2025-06-18 17:46:33,174 INFO Request: POST /event/ | User: root
2025-06-18 17:46:33,183 WARNING Bad Request: /event/
2025-06-18 17:47:29,588 INFO Request: POST /event/ | User: root
2025-06-18 17:47:29,597 WARNING Bad Request: /event/
2025-06-18 17:47:33,831 INFO Request: POST /event/ | User: root
2025-06-18 17:47:33,841 WARNING Bad Request: /event/
2025-06-18 17:47:42,266 INFO Request: POST /event/ | User: root
2025-06-18 17:47:42,277 WARNING Bad Request: /event/
2025-06-18 17:47:47,181 INFO Request: POST /event/ | User: root
2025-06-18 17:47:47,193 WARNING Bad Request: /event/
2025-06-18 17:48:08,016 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:48:08,899 INFO Watching for file changes with StatReloader
2025-06-18 17:48:17,676 INFO Request: GET /group/1/ | User: root
2025-06-18 17:48:24,771 INFO Request: POST /event/ | User: root
2025-06-18 17:48:35,985 INFO Request: DELETE /event/2. | User: 
2025-06-18 17:48:36,024 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:48:38,076 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_arfpfgC.jpg
2025-06-18 17:48:38,077 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_ZWekseM.jpg
2025-06-18 17:48:38,079 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_OxVU7vE.webm
2025-06-18 17:48:38,085 INFO Request: DELETE /event/2/ | User: root
2025-06-18 17:48:38,142 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:48:47,866 INFO Request: DELETE /event/2/ | User: root
2025-06-18 17:48:47,885 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:49:27,909 INFO Request: DELETE /event/2/ | User: root
2025-06-18 17:49:27,928 WARNING Not Found: /event/2/
2025-06-18 17:49:33,796 INFO Request: GET /event/2/ | User: root
2025-06-18 17:49:33,818 WARNING Not Found: /event/2/
2025-06-18 17:49:36,037 INFO Request: GET /event/ | User: root
2025-06-18 17:49:44,074 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-18 17:49:44,075 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-18 17:49:44,077 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-18 17:49:44,082 INFO Request: DELETE /event/1/ | User: root
2025-06-18 17:49:52,641 INFO Request: POST /event/ | User: root
2025-06-18 17:49:59,103 INFO Request: POST /event/ | User: root
2025-06-18 17:51:11,157 INFO Request: GET /event/4/ | User: root
2025-06-18 17:51:11,194 ERROR Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 130, in __call__
    return self._postprocess(request, response, toolbar)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 167, in _postprocess
    panel.generate_stats(request, response)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\history\panel.py", line 64, in generate_stats
    and request.body
        ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\http\request.py", line 378, in body
    raise RequestDataTooBig(
        "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."
    )
django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
2025-06-18 17:51:22,219 INFO Request: GET /event/ | User: 
2025-06-18 17:51:23,658 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:52:00,908 INFO Request: GET /group/ | User: 
2025-06-18 17:52:07,995 INFO Request: GET /group/1/ | User: 
2025-06-18 17:52:09,827 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:52:13,579 INFO Request: POST /__debug__/sql_select/ | User: 
2025-06-18 17:52:20,020 INFO Request: GET /event/ | User: 
2025-06-18 17:52:52,464 INFO D:\python\university_backend\university_backend\settings.py changed, reloading.
2025-06-18 17:52:53,135 INFO Watching for file changes with StatReloader
2025-06-18 17:52:54,563 INFO Request: GET /event/4/ | User: root
2025-06-18 17:52:58,714 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_VJQ7Zap.jpg
2025-06-18 17:52:58,715 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_S1XV1Qn.jpg
2025-06-18 17:52:58,716 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_DURSryt.webm
2025-06-18 17:52:58,719 INFO Request: DELETE /event/4/ | User: root
2025-06-18 17:53:07,603 INFO Request: GET /event/ | User: 
2025-06-18 17:53:09,179 INFO Request: GET /__debug__/render_panel/ | User: 
2025-06-18 17:53:28,108 INFO Request: GET /event/3/ | User: 
2025-06-18 17:53:52,064 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:54:05,476 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:57:49,989 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:57:50,652 INFO Watching for file changes with StatReloader
2025-06-18 17:58:02,294 ERROR Internal Server Error: /event/3/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'group_id' was declared on serializer EventSerializer, but has not been included in the 'fields' option.
2025-06-18 17:58:02,298 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:58:14,919 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-18 17:58:15,643 INFO Watching for file changes with StatReloader
2025-06-18 17:58:17,186 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:58:17,219 WARNING Bad Request: /event/3/
2025-06-18 17:58:23,428 INFO Request: PATCH /event/3/ | User: root
2025-06-18 17:58:36,337 INFO Request: POST /event/ | User: root
2025-06-18 17:59:16,349 INFO Watching for file changes with StatReloader
2025-06-18 17:59:18,782 INFO Request: GET /event/ | User: root
2025-06-18 17:59:24,053 INFO Request: GET /event/5/ | User: root
2025-06-18 17:59:26,973 INFO Request: GET /event/ | User: root
2025-06-18 18:00:47,746 INFO Watching for file changes with StatReloader
2025-06-18 18:00:49,854 INFO Request: POST /event/ | User: root
2025-06-18 18:18:23,771 INFO Watching for file changes with StatReloader
2025-06-18 18:18:26,480 INFO Request: POST /event/ | User: root
2025-06-18 18:18:30,103 INFO Request: GET /event/ | User: root
2025-06-18 18:19:52,485 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:19:53,502 INFO Watching for file changes with StatReloader
2025-06-18 18:20:43,566 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:20:44,197 INFO Watching for file changes with StatReloader
2025-06-18 18:21:18,921 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:21:19,537 INFO Watching for file changes with StatReloader
2025-06-18 18:21:38,687 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:21:39,363 INFO Watching for file changes with StatReloader
2025-06-18 18:22:32,542 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:22:33,132 INFO Watching for file changes with StatReloader
2025-06-18 18:22:45,150 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:22:45,795 INFO Watching for file changes with StatReloader
2025-06-18 18:22:49,540 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:22:50,154 INFO Watching for file changes with StatReloader
2025-06-18 18:24:23,978 INFO Watching for file changes with StatReloader
2025-06-18 18:24:25,989 INFO Request: GET / | User: 
2025-06-18 18:24:26,006 WARNING Not Found: /
2025-06-18 18:24:26,899 INFO Request: GET /admin/ | User: 
2025-06-18 18:24:26,950 INFO Request: GET /admin/login/ | User: 
2025-06-18 18:24:37,288 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:24:38,211 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:24:38,215 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:24:38,460 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:24:38,462 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:24:38,763 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:25:16,147 INFO Watching for file changes with StatReloader
2025-06-18 18:25:18,870 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:25:19,112 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:25:19,115 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:25:19,274 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:25:19,276 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:25:19,519 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:26:03,102 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:26:03,783 INFO Watching for file changes with StatReloader
2025-06-18 18:26:04,424 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:26:04,660 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:26:04,663 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:26:04,835 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:26:04,836 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:26:05,076 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:26:18,782 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:26:19,460 INFO Watching for file changes with StatReloader
2025-06-18 18:28:28,030 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:28:28,841 INFO Watching for file changes with StatReloader
2025-06-18 18:28:29,620 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:28:29,707 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:28:56,192 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:28:56,871 INFO Watching for file changes with StatReloader
2025-06-18 18:28:57,465 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:28:57,660 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type type is not JSON serializable
2025-06-18 18:28:57,662 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:28:57,817 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type type is not JSON serializable
2025-06-18 18:28:57,818 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:28:58,057 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:06,743 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:07,468 INFO Watching for file changes with StatReloader
2025-06-18 18:29:08,448 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:08,641 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:08,644 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:08,801 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:08,802 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:09,037 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:09,448 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:09,615 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:09,616 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:09,770 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:09,772 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:10,010 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:29,715 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:30,454 INFO Watching for file changes with StatReloader
2025-06-18 18:29:31,192 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:31,383 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:31,386 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:31,544 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:31,546 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:31,781 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:41,353 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:41,998 INFO Watching for file changes with StatReloader
2025-06-18 18:29:42,575 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:42,770 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:42,772 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:42,926 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:42,928 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:43,170 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:52,632 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:52,807 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:52,808 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:52,971 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:29:52,973 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:29:53,013 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:29:53,716 INFO Watching for file changes with StatReloader
2025-06-18 18:29:54,399 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:29:54,415 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:29:54,484 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:30:06,689 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:30:07,408 INFO Watching for file changes with StatReloader
2025-06-18 18:30:36,935 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:30:37,592 INFO Watching for file changes with StatReloader
2025-06-18 18:31:59,296 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:31:59,941 INFO Watching for file changes with StatReloader
2025-06-18 18:32:00,817 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:32:01,076 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:32:01,078 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:32:01,237 ERROR Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\python\university_backend\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type ellipsis is not JSON serializable
2025-06-18 18:32:01,238 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:32:01,488 INFO Request: GET /__debug__/history_sidebar/ | User: 
2025-06-18 18:32:12,886 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:32:13,682 INFO Watching for file changes with StatReloader
2025-06-18 18:32:14,387 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:32:14,470 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:32:42,139 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-18 18:32:42,858 INFO Watching for file changes with StatReloader
2025-06-18 18:32:43,530 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:32:43,617 INFO Request: GET /api/schema/ | User: 
2025-06-18 18:33:23,647 INFO Watching for file changes with StatReloader
2025-06-18 18:33:26,553 INFO Request: GET / | User: 
2025-06-18 18:33:26,571 WARNING Not Found: /
2025-06-18 18:33:27,393 INFO Request: GET /admin/ | User: 
2025-06-18 18:33:27,430 INFO Request: GET /admin/login/ | User: 
2025-06-18 18:33:28,056 INFO Request: GET /api/docs/ | User: 
2025-06-18 18:33:28,252 INFO Request: GET /api/schema/ | User: 
2025-06-19 12:05:44,778 INFO Watching for file changes with StatReloader
2025-06-19 12:08:58,908 INFO Request: POST /api/token/ | User: 
2025-06-19 12:09:07,668 INFO Request: GET /event/ | User: root
2025-06-19 12:09:15,938 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:00,611 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 12:10:01,339 INFO Watching for file changes with StatReloader
2025-06-19 12:10:03,139 ERROR Internal Server Error: /event/7/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "D:\python\university_backend\event_api\views.py", line 148, in get_object
    return Event.objects.get(pk=self.kwargs['pk']).prefetch_related('photos', 'videos').select_related('author')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Event' object has no attribute 'prefetch_related'
2025-06-19 12:10:03,142 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:24,940 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 12:10:25,620 INFO Watching for file changes with StatReloader
2025-06-19 12:10:27,072 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:39,058 INFO Request: GET /event/7 | User: 
2025-06-19 12:10:39,260 INFO Request: GET /event/7/ | User: root
2025-06-19 12:10:47,071 INFO Request: GET /event/ | User: root
2025-06-19 12:12:42,636 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 12:12:43,362 INFO Watching for file changes with StatReloader
2025-06-19 12:12:48,263 INFO Request: GET /event/7. | User: 
2025-06-19 12:12:48,298 WARNING Not Found: /event/7.
2025-06-19 12:12:49,399 INFO Request: GET /event/7/ | User: root
2025-06-19 12:13:02,937 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 12:13:03,633 INFO Watching for file changes with StatReloader
2025-06-19 12:13:05,027 INFO Request: GET /event/7/ | User: root
2025-06-19 14:11:16,668 INFO Watching for file changes with StatReloader
2025-06-19 14:11:26,365 INFO Request: GET /event/7/ | User: 
2025-06-19 14:11:26,396 WARNING Unauthorized: /event/7/
2025-06-19 14:11:34,739 INFO Request: POST /api/token/ | User: 
2025-06-19 14:11:42,650 INFO Request: GET /event/7/ | User: root
2025-06-19 14:11:47,677 INFO Request: GET /event/ | User: root
2025-06-19 14:11:59,885 INFO Request: POST /event/ | User: root
2025-06-19 14:12:19,718 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:12:20,491 INFO Watching for file changes with StatReloader
2025-06-19 14:15:27,694 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 14:15:29,176 INFO Watching for file changes with StatReloader
2025-06-19 14:16:12,333 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 14:16:13,087 INFO Watching for file changes with StatReloader
2025-06-19 14:16:29,254 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:16:30,048 INFO Watching for file changes with StatReloader
2025-06-19 14:16:32,158 INFO Request: GET /event/ | User: root
2025-06-19 14:16:46,048 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-19 14:16:46,049 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-19 14:16:46,053 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:16:46,058 INFO Request: DELETE /event/3/ | User: root
2025-06-19 14:16:49,560 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_ZH3mhoq.jpg
2025-06-19 14:16:49,561 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_tvXZpbf.jpg
2025-06-19 14:16:49,565 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_bfQreOa.webm
2025-06-19 14:16:49,570 INFO Request: DELETE /event/5/ | User: root
2025-06-19 14:16:52,096 ERROR Internal Server Error: /event/5/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "D:\python\university_backend\event_api\views.py", line 148, in get_object
    return Event.objects.get(pk=self.kwargs['pk'])
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
event_api.models.Event.DoesNotExist: Event matching query does not exist.
2025-06-19 14:16:52,100 INFO Request: GET /event/5/ | User: root
2025-06-19 14:17:02,383 INFO Request: GET /event/ | User: root
2025-06-19 14:17:16,574 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_E9GWBde.jpg
2025-06-19 14:17:16,575 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_9iCjBni.jpg
2025-06-19 14:17:16,577 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_YqArH0A.webm
2025-06-19 14:17:16,581 INFO Request: DELETE /event/6/ | User: root
2025-06-19 14:17:19,384 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_ykiOwa9.jpg
2025-06-19 14:17:19,384 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_vTNCIWl.jpg
2025-06-19 14:17:19,387 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_VHGtW1Y.webm
2025-06-19 14:17:19,390 INFO Request: DELETE /event/7/ | User: root
2025-06-19 14:17:22,232 INFO Request: GET /event/ | User: root
2025-06-19 14:17:25,745 INFO Request: GET /event/8/ | User: root
2025-06-19 14:17:48,583 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:17:49,351 INFO Watching for file changes with StatReloader
2025-06-19 14:17:50,932 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'author' was declared on serializer ListEventSerializer, but has not been included in the 'fields' option.
2025-06-19 14:17:50,936 INFO Request: GET /event/ | User: root
2025-06-19 14:18:16,022 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:18:16,671 INFO Watching for file changes with StatReloader
2025-06-19 14:18:18,002 INFO Request: GET /event/ | User: root
2025-06-19 14:19:01,657 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:19:02,958 INFO Watching for file changes with StatReloader
2025-06-19 14:19:04,418 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 386, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 374, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1081, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 1177, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'first_photo' was declared on serializer ListEventSerializer, but has not been included in the 'fields' option.
2025-06-19 14:19:04,420 INFO Request: GET /event/ | User: root
2025-06-19 14:19:29,520 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:19:30,251 INFO Watching for file changes with StatReloader
2025-06-19 14:19:31,752 INFO Request: GET /event/ | User: root
2025-06-19 14:20:18,375 INFO Request: GET /event/ | User: root
2025-06-19 14:20:40,439 INFO Request: GET /event/ | User: root
2025-06-19 14:20:51,364 INFO Request: GET /event/ | User: root
2025-06-19 14:21:09,538 INFO Request: GET /event/8. | User: 
2025-06-19 14:21:09,566 WARNING Not Found: /event/8.
2025-06-19 14:21:11,050 INFO Request: GET /event/8/ | User: root
2025-06-19 14:21:48,657 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:21:49,546 INFO Watching for file changes with StatReloader
2025-06-19 14:21:50,746 INFO Request: GET /event/8/ | User: root
2025-06-19 14:22:30,531 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:22:31,294 INFO Watching for file changes with StatReloader
2025-06-19 14:22:32,568 INFO Request: GET /event/ | User: root
2025-06-19 14:24:59,319 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:25:00,463 INFO Watching for file changes with StatReloader
2025-06-19 14:25:04,469 ERROR Internal Server Error: /event/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 497, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 380, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 375, in fields
    fields[key] = value
    ~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\utils\serializer_helpers.py", line 167, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\fields.py", line 358, in bind
    assert self.source != field_name, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: It is redundant to specify `source='group'` on field 'PrimaryKeyRelatedField' in serializer 'EventSerializer', because it is the same as the field name. Remove the `source` keyword argument.
2025-06-19 14:25:04,472 INFO Request: POST /event/ | User: root
2025-06-19 14:25:23,504 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:25:24,251 INFO Watching for file changes with StatReloader
2025-06-19 14:25:31,069 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:25:31,763 INFO Watching for file changes with StatReloader
2025-06-19 14:25:32,719 INFO Request: POST /event/ | User: root
2025-06-19 14:26:00,327 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:26:01,056 INFO Watching for file changes with StatReloader
2025-06-19 14:26:02,239 INFO Request: POST /event/ | User: root
2025-06-19 14:26:11,769 INFO Request: GET /event/ | User: root
2025-06-19 14:26:32,110 INFO Request: GET /event/ | User: root
2025-06-19 14:26:44,644 INFO Request: GET /admin/ | User: 
2025-06-19 14:26:44,813 INFO Request: GET /admin/login/ | User: 
2025-06-19 14:26:44,963 INFO Request: GET /favicon.ico | User: 
2025-06-19 14:26:44,978 WARNING Not Found: /favicon.ico
2025-06-19 14:26:46,900 INFO Request: POST /admin/login/ | User: root
2025-06-19 14:26:47,149 INFO Request: GET /admin/ | User: root
2025-06-19 14:26:49,492 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:26:49,650 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:26:53,035 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:26:54,011 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_voo1bvf.jpg
2025-06-19 14:26:54,012 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_tFEiHkL.webm
2025-06-19 14:26:54,014 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-19 14:26:54,014 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-19 14:26:54,016 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:26:54,017 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_gItzWUQ.jpg
2025-06-19 14:26:54,017 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_rEo7gSN.jpg
2025-06-19 14:26:54,019 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_4m2ZX2y.webm
2025-06-19 14:26:54,022 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:26:54,142 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:26:54,225 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:27:09,411 INFO Request: GET /event/ | User: root
2025-06-19 14:27:50,849 INFO Request: POST /event/ | User: root
2025-06-19 14:27:50,862 WARNING Bad Request: /event/
2025-06-19 14:28:00,107 INFO Request: POST /event/ | User: root
2025-06-19 14:28:13,518 INFO Request: GET /event/ | User: root
2025-06-19 14:28:25,479 INFO Request: GET /event/11/ | User: root
2025-06-19 14:29:04,247 INFO Request: PATCH /event/11/ | User: root
2025-06-19 14:29:09,962 INFO Request: GET /event/11/ | User: root
2025-06-19 14:29:27,403 INFO Request: GET /event/11/ | User: root
2025-06-19 14:29:37,908 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-19 14:29:37,908 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-19 14:29:37,908 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_qUjpdDs.jpg
2025-06-19 14:29:37,909 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_1CwMmnS.jpg
2025-06-19 14:29:37,912 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:29:37,916 INFO Request: DELETE /event/11/ | User: root
2025-06-19 14:29:57,516 INFO Request: POST /event/ | User: root
2025-06-19 14:29:57,523 WARNING Bad Request: /event/
2025-06-19 14:30:01,997 INFO Request: POST /event/ | User: root
2025-06-19 14:30:12,505 INFO Request: GET /event/ | User: root
2025-06-19 14:30:30,008 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:30:30,723 INFO Watching for file changes with StatReloader
2025-06-19 14:30:32,166 INFO Request: POST /event/ | User: root
2025-06-19 14:30:35,991 INFO Request: GET /event/ | User: root
2025-06-19 14:30:41,443 INFO Request: GET /event/13/ | User: root
2025-06-19 14:30:55,483 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_gOl1fVX.jpg
2025-06-19 14:30:55,484 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_kri3vcf.jpg
2025-06-19 14:30:55,487 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_PyqW8fl.webm
2025-06-19 14:30:55,492 INFO Request: DELETE /event/13/ | User: root
2025-06-19 14:31:03,358 INFO Request: GET /event/12/ | User: root
2025-06-19 14:31:12,052 INFO Request: PATCH /event/12/ | User: root
2025-06-19 14:31:15,835 INFO Request: GET /event/12/ | User: root
2025-06-19 14:31:31,936 INFO Request: PATCH /event/12/ | User: root
2025-06-19 14:31:33,949 INFO Request: GET /event/12/ | User: root
2025-06-19 14:31:55,016 INFO Request: POST /event/ | User: root
2025-06-19 14:31:55,025 WARNING Bad Request: /event/
2025-06-19 14:32:19,623 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-19 14:32:20,306 INFO Watching for file changes with StatReloader
2025-06-19 14:32:24,772 INFO Request: POST /event/ | User: root
2025-06-19 14:32:30,288 INFO Request: GET /event/14/ | User: root
2025-06-19 14:33:07,560 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-19 14:33:08,219 INFO Watching for file changes with StatReloader
2025-06-19 14:33:18,490 INFO Request: GET /event/14/ | User: root
2025-06-19 14:33:22,204 INFO Request: POST /event/ | User: root
2025-06-19 14:33:22,217 WARNING Bad Request: /event/
2025-06-19 14:36:49,343 INFO Watching for file changes with StatReloader
2025-06-19 14:36:51,392 INFO Request: GET / | User: root
2025-06-19 14:36:51,419 WARNING Not Found: /
2025-06-19 14:36:55,063 INFO Request: GET /admin/ | User: root
2025-06-19 14:36:58,304 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:36:58,425 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:01,631 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:37:03,313 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-19 14:37:03,317 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-19 14:37:03,549 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-19 14:37:03,633 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:05,164 INFO Request: GET /admin/event_api/event/add/ | User: root
2025-06-19 14:37:05,269 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:15,578 INFO Request: GET /admin/event_api/event/add/ | User: root
2025-06-19 14:37:15,721 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-19 14:37:15,863 INFO Request: GET /favicon.ico | User: root
2025-06-19 14:37:15,895 WARNING Not Found: /favicon.ico
2025-06-19 14:37:32,396 INFO Request: POST /event/ | User: root
2025-06-19 14:37:32,405 WARNING Bad Request: /event/
2025-06-19 14:37:38,888 INFO Request: POST /event/ | User: root
2025-06-20 14:03:41,892 INFO Watching for file changes with StatReloader
2025-06-20 14:03:47,643 INFO Request: POST /api/token/ | User: 
2025-06-20 14:04:00,737 INFO Request: GET /me/ | User: root
2025-06-20 14:04:41,554 INFO Request: POST /api/token/ | User: 
2025-06-20 14:04:41,570 WARNING Unauthorized: /api/token/
2025-06-20 14:04:46,908 INFO Request: POST /api/token/ | User: 
2025-06-20 14:04:56,138 INFO Request: GET /me/ | User: student1
2025-06-20 14:18:53,324 INFO Request: POST /api/token/ | User: 
2025-06-20 14:19:02,061 INFO Request: GET /me/ | User: root
2025-06-20 14:19:02,311 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 14:19:02,376 INFO Request: GET /me/ | User: root
2025-06-20 14:25:10,928 INFO Request: POST /api/token/ | User: 
2025-06-20 14:25:10,938 WARNING Unauthorized: /api/token/
2025-06-20 14:25:32,835 INFO Request: POST /api/token/ | User: 
2025-06-20 14:25:44,063 INFO Request: GET /me/ | User: student1
2025-06-20 14:25:44,246 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 14:25:44,311 INFO Request: GET /me/ | User: student1
2025-06-20 14:27:30,154 INFO Request: GET /me/ | User: student1
2025-06-20 14:27:45,074 INFO Request: POST /api/token/ | User: 
2025-06-20 14:30:34,726 INFO Request: POST /api/token/ | User: 
2025-06-20 14:30:42,871 INFO Request: POST /api/token/ | User: 
2025-06-20 14:30:42,887 WARNING Unauthorized: /api/token/
2025-06-20 14:30:56,834 INFO Request: GET /me/ | User: root
2025-06-20 14:30:56,994 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 14:30:57,058 INFO Request: GET /me/ | User: root
2025-06-20 14:32:06,067 INFO Request: POST /api/token/ | User: 
2025-06-20 14:32:09,654 INFO Request: POST /api/token/ | User: 
2025-06-20 14:32:09,662 WARNING Unauthorized: /api/token/
2025-06-20 14:32:38,434 INFO Request: POST /api/token/ | User: 
2025-06-20 14:32:41,057 INFO Request: POST /api/token/ | User: 
2025-06-20 14:32:41,068 WARNING Unauthorized: /api/token/
2025-06-20 14:33:21,399 INFO Request: POST /api/token/ | User: 
2025-06-20 14:33:25,690 INFO Request: GET /me/ | User: root
2025-06-20 14:33:25,874 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 14:33:25,948 INFO Request: GET /me/ | User: root
2025-06-20 15:24:37,506 INFO Request: GET /me/ | User: root
2025-06-20 15:38:38,686 INFO Request: POST /api/token/ | User: 
2025-06-20 15:38:44,124 INFO Request: GET /me/ | User: root
2025-06-20 15:38:44,450 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 15:38:44,523 INFO Request: GET /me/ | User: root
2025-06-20 15:40:02,912 INFO Request: POST /api/token/ | User: 
2025-06-20 15:40:08,283 INFO Request: GET /me/ | User: root
2025-06-20 15:40:08,470 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 15:40:08,534 INFO Request: GET /me/ | User: root
2025-06-20 15:43:22,066 INFO Request: POST /api/token/ | User: 
2025-06-20 15:44:44,045 INFO Request: POST /api/token/ | User: 
2025-06-20 15:44:52,174 INFO Request: GET /me/ | User: student1
2025-06-20 15:44:52,366 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 15:44:52,520 INFO Request: GET /me/ | User: student1
2025-06-20 15:48:59,290 INFO Request: POST /api/token/ | User: 
2025-06-20 15:49:06,184 INFO Request: GET /me/ | User: root
2025-06-20 15:49:06,366 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 15:49:06,426 INFO Request: GET /me/ | User: root
2025-06-20 15:55:24,439 INFO Request: GET /me/ | User: root
2025-06-20 15:55:38,001 INFO Request: POST /api/token/ | User: 
2025-06-20 15:55:42,748 INFO Request: GET /me/ | User: root
2025-06-20 15:55:43,026 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 15:55:43,089 INFO Request: GET /me/ | User: root
2025-06-20 15:56:58,362 INFO Request: GET /me/ | User: root
2025-06-20 16:00:37,634 INFO D:\python\university_backend\usercontrol_api\urls.py changed, reloading.
2025-06-20 16:00:38,368 INFO Watching for file changes with StatReloader
2025-06-20 16:08:04,346 INFO Request: GET /me/ | User: root
2025-06-20 16:14:21,898 INFO Request: GET /me/ | User: root
2025-06-20 16:16:19,692 INFO Request: GET /me/ | User: root
2025-06-20 16:19:02,574 INFO Request: GET /me/ | User: root
2025-06-20 16:25:52,632 INFO Request: GET /me/ | User: root
2025-06-20 16:28:27,416 INFO Watching for file changes with StatReloader
2025-06-20 16:28:33,765 INFO Request: POST /api/token/ | User: 
2025-06-20 16:28:41,628 INFO Request: GET /me/ | User: student1
2025-06-20 16:29:09,468 INFO Request: GET /me/ | User: student1
2025-06-20 16:29:20,606 INFO Request: GET /me/ | User: student1
2025-06-20 16:29:26,344 INFO Request: GET /me/ | User: student1
2025-06-20 16:29:36,616 INFO Request: GET /me/ | User: 
2025-06-20 16:29:36,630 WARNING Unauthorized: /me/
2025-06-20 16:30:47,126 INFO Request: POST /api/token/ | User: 
2025-06-20 16:30:50,524 INFO Request: GET /me/ | User: root
2025-06-20 16:30:50,796 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:30:50,852 INFO Request: GET /me/ | User: root
2025-06-20 16:33:52,291 INFO Request: POST /api/token/ | User: 
2025-06-20 16:33:55,292 INFO Request: GET /me/ | User: root
2025-06-20 16:33:55,477 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:33:55,555 INFO Request: GET /me/ | User: root
2025-06-20 16:34:02,986 INFO Request: GET /me/ | User: root
2025-06-20 16:34:08,615 INFO Request: GET /me/ | User: root
2025-06-20 16:37:52,012 INFO Watching for file changes with StatReloader
2025-06-20 16:37:56,698 INFO Request: POST /api/token/ | User: 
2025-06-20 16:38:15,130 INFO Request: POST /api/token/ | User: 
2025-06-20 16:38:21,992 INFO Request: GET /me/ | User: root
2025-06-20 16:38:52,034 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:38:52,048 WARNING Bad Request: /api/token/refresh/
2025-06-20 16:39:26,905 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:42:26,508 INFO Request: GET /me/ | User: 
2025-06-20 16:42:26,529 WARNING Unauthorized: /me/
2025-06-20 16:43:05,419 INFO Request: POST /api/token/ | User: 
2025-06-20 16:43:16,155 INFO Request: GET /me/ | User: root
2025-06-20 16:43:16,364 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:43:16,415 INFO Request: GET /me/ | User: root
2025-06-20 16:43:22,796 INFO Request: GET /me/ | User: root
2025-06-20 16:43:22,991 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:43:23,043 INFO Request: GET /me/ | User: root
2025-06-20 16:49:02,941 INFO Request: GET /me/ | User: root
2025-06-20 16:49:03,259 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:49:03,318 INFO Request: GET /me/ | User: root
2025-06-20 16:49:36,054 INFO Request: POST /api/token/ | User: 
2025-06-20 16:49:41,848 INFO Request: GET /me/ | User: root
2025-06-20 16:49:42,172 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:49:42,347 INFO Request: GET /me/ | User: root
2025-06-20 16:49:47,382 INFO Request: GET /me/ | User: root
2025-06-20 16:49:47,560 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 16:49:47,640 INFO Request: GET /me/ | User: root
2025-06-20 17:07:53,835 INFO Request: GET /me/ | User: root
2025-06-20 17:08:38,646 INFO Request: GET /me/ | User: root
2025-06-20 17:08:40,378 INFO Request: GET /me/ | User: root
2025-06-20 17:08:43,334 INFO Request: GET /me/ | User: 
2025-06-20 17:08:43,343 WARNING Unauthorized: /me/
2025-06-20 17:08:48,362 INFO Request: GET /me/ | User: root
2025-06-20 17:10:07,214 INFO D:\python\university_backend\university_backend\settings.py changed, reloading.
2025-06-20 17:10:07,850 INFO Watching for file changes with StatReloader
2025-06-20 17:10:16,862 INFO Watching for file changes with StatReloader
2025-06-20 17:10:34,347 INFO Request: POST /api/token/ | User: 
2025-06-20 17:10:39,020 INFO Request: GET /me/ | User: root
2025-06-20 17:10:41,962 INFO Request: GET /me/ | User: root
2025-06-20 17:10:48,224 INFO Request: POST /api/token/ | User: 
2025-06-20 17:10:55,984 INFO Request: GET /me/ | User: root
2025-06-20 17:11:32,188 INFO Request: GET /me/ | User: root
2025-06-20 17:11:43,357 INFO Request: GET /me/ | User: root
2025-06-20 17:11:47,577 INFO Request: GET /me/ | User: root
2025-06-20 17:11:53,326 INFO Request: GET /me/ | User: 
2025-06-20 17:11:53,343 WARNING Unauthorized: /me/
2025-06-20 17:11:59,260 INFO Request: GET /me/ | User: 
2025-06-20 17:11:59,282 WARNING Unauthorized: /me/
2025-06-20 17:12:31,041 INFO Request: GET /me/ | User: 
2025-06-20 17:12:31,048 WARNING Unauthorized: /me/
2025-06-20 17:13:22,333 INFO Request: GET /me/ | User: 
2025-06-20 17:13:22,340 WARNING Unauthorized: /me/
2025-06-20 17:13:53,342 INFO Request: POST /api/token/ | User: 
2025-06-20 17:13:56,575 INFO Request: GET /me/ | User: root
2025-06-20 17:14:46,784 INFO Request: GET /me/ | User: root
2025-06-20 17:15:22,003 INFO Request: GET /me/ | User: 
2025-06-20 17:15:22,019 WARNING Unauthorized: /me/
2025-06-20 17:20:47,982 INFO Request: POST /api/token/ | User: 
2025-06-20 17:20:50,017 INFO Request: GET /me/ | User: root
2025-06-20 17:20:53,326 INFO Request: GET /me/ | User: root
2025-06-20 17:21:58,879 INFO Request: GET /me/ | User: 
2025-06-20 17:21:58,898 WARNING Unauthorized: /me/
2025-06-20 17:22:20,015 INFO Request: GET /me/ | User: 
2025-06-20 17:22:20,030 WARNING Unauthorized: /me/
2025-06-20 17:23:37,848 INFO Request: POST /api/token/ | User: 
2025-06-20 17:23:41,263 INFO Request: GET /me/ | User: root
2025-06-20 17:24:30,457 INFO Request: GET /me/ | User: root
2025-06-20 17:24:53,572 INFO Request: GET /me/ | User: 
2025-06-20 17:24:53,595 WARNING Unauthorized: /me/
2025-06-20 17:25:14,749 INFO Request: GET /me/ | User: 
2025-06-20 17:25:14,756 WARNING Unauthorized: /me/
2025-06-20 17:27:01,376 INFO Request: GET /me/ | User: 
2025-06-20 17:27:01,386 WARNING Unauthorized: /me/
2025-06-20 17:28:57,227 INFO Request: GET /me/ | User: 
2025-06-20 17:28:57,247 WARNING Unauthorized: /me/
2025-06-20 17:29:14,839 INFO Request: GET /me/ | User: 
2025-06-20 17:29:14,859 WARNING Unauthorized: /me/
2025-06-20 17:29:48,827 INFO Request: POST /api/token/ | User: 
2025-06-20 17:29:54,670 INFO Request: GET /me/ | User: student1
2025-06-20 17:30:50,365 INFO Request: GET /me/ | User: 
2025-06-20 17:30:50,371 WARNING Unauthorized: /me/
2025-06-20 17:43:50,488 INFO Request: POST /api/token/ | User: 
2025-06-20 17:45:39,349 INFO Request: POST /api/token/ | User: 
2025-06-20 17:45:43,037 INFO Request: GET /me/ | User: student1
2025-06-20 17:45:46,934 INFO Request: GET /me/ | User: student1
2025-06-20 17:49:38,047 INFO Request: POST /api/token/ | User: 
2025-06-20 17:49:38,058 WARNING Unauthorized: /api/token/
2025-06-20 17:49:55,135 INFO Request: POST /api/token/ | User: 
2025-06-20 17:49:57,738 INFO Request: GET /me/ | User: root
2025-06-20 17:50:48,103 INFO Request: GET /me/ | User: root
2025-06-20 17:51:20,335 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 17:51:20,410 INFO Request: GET /me/ | User: root
2025-06-20 17:51:56,857 INFO Request: GET /me/ | User: root
2025-06-20 17:54:50,928 INFO Request: POST /api/token/ | User: 
2025-06-20 17:54:57,625 INFO Request: GET /me/ | User: student1
2025-06-20 17:56:34,059 INFO Request: POST /api/token/refresh/ | User: 
2025-06-20 17:56:34,119 INFO Request: GET /me/ | User: student1
2025-06-20 17:56:47,062 INFO Request: GET /me/ | User: student1
2025-06-20 21:05:41,085 INFO Watching for file changes with StatReloader
2025-06-20 21:06:04,799 INFO Watching for file changes with StatReloader
2025-06-20 21:07:22,934 INFO Watching for file changes with StatReloader
2025-06-20 21:07:31,741 ERROR Internal Server Error: /api/token/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: Œÿ»¡ ¿:  ÒÚÓÎ·Âˆ usercontrol_api_user.tg_id ÌÂ ÒÛ˘ÂÒÚ‚ÛÂÚ
LINE 1: ..._user"."role", "usercontrol_api_user"."group_id", "usercontr...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\contrib\auth\backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: Œÿ»¡ ¿:  ÒÚÓÎ·Âˆ usercontrol_api_user.tg_id ÌÂ ÒÛ˘ÂÒÚ‚ÛÂÚ
LINE 1: ..._user"."role", "usercontrol_api_user"."group_id", "usercontr...
                                                             ^

2025-06-20 21:07:31,757 INFO Request: POST /api/token/ | User: 
2025-06-20 21:07:57,950 INFO Watching for file changes with StatReloader
2025-06-20 21:08:00,643 INFO Request: POST /api/token/ | User: 
2025-06-20 21:08:11,356 INFO Request: GET /users/ | User: root
2025-06-20 21:08:25,023 INFO Request: GET /users/role=student | User: 
2025-06-20 21:08:25,083 INFO Request: GET /users/role=student/ | User: root
2025-06-20 21:08:25,091 WARNING Not Found: /users/role=student/
2025-06-20 21:08:49,313 INFO Request: GET /users/r | User: 
2025-06-20 21:08:49,398 INFO Request: GET /users/r/ | User: root
2025-06-20 21:08:49,415 WARNING Not Found: /users/r/
2025-06-20 21:08:50,697 INFO Request: GET /users/ | User: root
2025-06-20 21:08:52,196 INFO Request: GET /users/2/ | User: root
2025-06-20 21:08:53,685 INFO Request: GET /users/ | User: root
2025-06-20 21:08:56,667 INFO Request: GET /users/role=student | User: 
2025-06-20 21:08:56,743 INFO Request: GET /users/role=student/ | User: root
2025-06-20 21:08:56,760 WARNING Not Found: /users/role=student/
2025-06-20 21:09:01,658 INFO Request: GET /users/role=teacher | User: 
2025-06-20 21:09:01,725 INFO Request: GET /users/role=teacher/ | User: root
2025-06-20 21:09:01,735 WARNING Not Found: /users/role=teacher/
2025-06-20 21:09:10,026 INFO Request: GET /users/ | User: root
2025-06-20 21:09:14,482 INFO Request: GET /users/ | User: root
2025-06-20 21:09:17,060 INFO Request: GET /users/ | User: root
2025-06-20 21:09:25,033 INFO Request: GET /users/ | User: root
2025-06-20 21:09:27,477 INFO Request: GET /users/ | User: root
2025-06-20 21:09:31,519 INFO Request: GET /users/ | User: root
2025-06-20 21:09:34,178 INFO Request: GET /users/ | User: root
2025-06-20 21:14:52,988 INFO Watching for file changes with StatReloader
2025-06-20 21:15:43,032 INFO Request: POST /api/token/ | User: 
2025-06-20 21:15:43,155 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-20 21:20:02,844 INFO Request: GET /users/ | User: root
2025-06-20 21:23:08,426 INFO Request: GET /users/ | User: root
2025-06-20 21:25:33,401 INFO Request: GET /users/ | User: root
2025-06-20 21:27:24,598 INFO Request: POST /api/token/ | User: 
2025-06-20 21:27:24,676 INFO Request: PATCH /user/link_telegram/ | User: student1
2025-06-20 21:27:27,154 INFO Request: GET /users/ | User: student1
2025-06-21 11:25:44,245 INFO Watching for file changes with StatReloader
2025-06-21 11:26:19,840 INFO Request: POST /api/token/ | User: 
2025-06-21 11:26:20,113 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 11:26:35,221 INFO Request: GET /me/ | User: root
2025-06-21 11:26:53,298 INFO Request: GET /users/ | User: root
2025-06-21 11:28:48,611 INFO Request: GET /me/ | User: root
2025-06-21 11:28:53,536 INFO Request: GET /users/ | User: root
2025-06-21 11:29:09,147 INFO Request: POST /api/token/ | User: 
2025-06-21 11:29:09,215 INFO Request: PATCH /user/link_telegram/ | User: student1
2025-06-21 11:29:22,995 INFO Request: GET /users/ | User: student1
2025-06-21 11:35:53,920 INFO Request: POST /api/token/ | User: 
2025-06-21 11:35:53,936 WARNING Unauthorized: /api/token/
2025-06-21 11:36:59,036 INFO Request: POST /api/token/ | User: 
2025-06-21 11:36:59,115 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 11:38:13,717 INFO Request: POST /api/token/ | User: 
2025-06-21 11:38:13,778 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 11:38:20,688 INFO Request: GET /me/ | User: root
2025-06-21 11:38:25,370 INFO Request: GET /users/ | User: root
2025-06-21 11:42:22,841 INFO Request: GET /users/ | User: 
2025-06-21 11:42:22,850 WARNING Unauthorized: /users/
2025-06-21 11:42:26,160 INFO Request: POST /api/token/ | User: 
2025-06-21 11:42:36,612 INFO Request: GET /users/ | User: root
2025-06-21 11:43:45,133 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:43:45,860 INFO Watching for file changes with StatReloader
2025-06-21 11:44:12,223 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:44:12,913 INFO Watching for file changes with StatReloader
2025-06-21 11:44:48,813 INFO Watching for file changes with StatReloader
2025-06-21 11:44:52,797 INFO Request: GET /users/ | User: root
2025-06-21 11:45:20,451 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:45:21,150 INFO Watching for file changes with StatReloader
2025-06-21 11:45:31,017 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:45:31,687 INFO Watching for file changes with StatReloader
2025-06-21 11:48:24,318 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:48:24,974 INFO Watching for file changes with StatReloader
2025-06-21 11:48:25,989 INFO Request: GET /users/ | User: root
2025-06-21 11:48:33,103 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:48:36,520 INFO Request: GET /users/ | User: root
2025-06-21 11:48:40,709 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:48:42,599 ERROR Internal Server Error: /users/1352441814/
Traceback (most recent call last):
  File "D:\python\university_backend\usercontrol_api\views.py", line 119, in get_object
    return self.queryset.get(tg_id=tg_id)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
usercontrol_api.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\usercontrol_api\views.py", line 128, in retrieve
    serializer = self.get_serializer(self.get_object())
                                     ~~~~~~~~~~~~~~~^^
  File "D:\python\university_backend\usercontrol_api\views.py", line 121, in get_object
    raise KeyError("œÓÎ¸ÁÓ‚‡ÚÂÎ¸ Ò Ú‡ÍËÏ telegram ID ÌÂ Ì‡È‰ÂÌ")
KeyError: 'œÓÎ¸ÁÓ‚‡ÚÂÎ¸ Ò Ú‡ÍËÏ telegram ID ÌÂ Ì‡È‰ÂÌ'
2025-06-21 11:48:42,602 INFO Request: GET /users/1352441814/ | User: root
2025-06-21 11:48:58,250 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:50:04,496 INFO Request: GET /me/ | User: root
2025-06-21 11:50:08,746 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:50:28,180 INFO Request: POST /api/token/ | User: 
2025-06-21 11:50:28,190 WARNING Unauthorized: /api/token/
2025-06-21 11:50:48,069 INFO Request: POST /api/token/ | User: 
2025-06-21 11:50:48,127 INFO Request: PATCH /user/link_telegram/ | User: student1
2025-06-21 11:52:15,439 INFO Request: POST /api/token/ | User: 
2025-06-21 11:52:15,546 INFO Request: PATCH /user/link_telegram/ | User: student1
2025-06-21 11:52:17,684 INFO Request: GET /me/ | User: student1
2025-06-21 11:52:24,094 INFO Request: GET /users/1352441813/ | User: student1
2025-06-21 11:53:35,224 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:53:35,922 INFO Watching for file changes with StatReloader
2025-06-21 11:53:37,482 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:53:40,715 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:53:41,415 INFO Watching for file changes with StatReloader
2025-06-21 11:53:42,608 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:53:43,922 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:53:44,871 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 11:53:49,235 INFO D:\python\university_backend\usercontrol_api\views.py changed, reloading.
2025-06-21 11:53:49,917 INFO Watching for file changes with StatReloader
2025-06-21 11:53:54,448 INFO Watching for file changes with StatReloader
2025-06-21 11:54:22,780 INFO Request: POST /api/token/ | User: 
2025-06-21 11:54:22,880 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 11:54:35,064 INFO Request: GET /me/ | User: root
2025-06-21 11:54:39,123 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:04:46,106 INFO Watching for file changes with StatReloader
2025-06-21 13:05:22,625 INFO Request: POST /api/token/ | User: 
2025-06-21 13:05:22,733 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 13:05:24,016 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:06:46,586 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:07:38,685 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:07:43,460 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:10:07,297 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:22:18,391 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:25:31,156 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:25:34,846 INFO Request: GET /group/ | User: root
2025-06-21 13:26:02,324 INFO Request: POST /api/token/ | User: 
2025-06-21 13:26:17,305 INFO Request: POST /group/ | User: root
2025-06-21 13:27:43,743 INFO Request: POST /group/ | User: root
2025-06-21 13:30:27,992 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:30:41,251 INFO Request: GET /group/ | User: root
2025-06-21 13:37:27,107 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:37:30,808 INFO Request: GET /group/ | User: root
2025-06-21 13:44:51,133 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:44:55,588 INFO Request: GET /group/ | User: root
2025-06-21 13:54:53,826 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:55:02,896 INFO Request: GET /group/ | User: root
2025-06-21 13:58:17,724 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:58:21,135 INFO Request: GET /group/ | User: root
2025-06-21 13:59:40,135 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 13:59:46,680 INFO Request: GET /group/ | User: root
2025-06-21 14:01:04,898 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:01:09,298 INFO Request: GET /group/ | User: root
2025-06-21 14:04:42,174 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:04:47,646 INFO Request: GET /group/ | User: root
2025-06-21 14:14:27,308 INFO Request: POST /api/token/refresh/ | User: 
2025-06-21 14:14:27,368 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:14:42,393 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:14:49,665 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:14:53,258 INFO Request: GET /group/ | User: root
2025-06-21 14:16:33,285 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:16:36,937 INFO Request: GET /group/ | User: root
2025-06-21 14:17:28,670 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:17:33,239 INFO Request: GET /group/ | User: root
2025-06-21 14:31:15,596 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:31:20,792 INFO Request: GET /group/ | User: root
2025-06-21 14:36:32,521 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:36:32,577 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:41:53,024 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 14:42:05,413 INFO Request: GET /group/ | User: root
2025-06-21 15:10:04,735 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:10:09,647 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:10:16,393 INFO Request: GET /group/ | User: root
2025-06-21 15:14:50,079 INFO Request: POST /api/token/refresh/ | User: 
2025-06-21 15:14:50,137 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:16:11,962 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:18:43,812 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:18:50,241 INFO Request: GET /group/ | User: root
2025-06-21 15:18:57,400 INFO Request: POST /event/ | User: root
2025-06-21 15:20:56,005 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:21:05,589 INFO Request: GET /group/ | User: root
2025-06-21 15:21:12,818 INFO Request: POST /event/ | User: root
2025-06-21 15:21:38,440 INFO Request: POST /api/token/ | User: 
2025-06-21 15:21:55,366 INFO Request: GET /event/17/ | User: root
2025-06-21 15:22:40,771 INFO Request: POST /api/token/ | User: 
2025-06-21 15:22:40,938 INFO Request: PATCH /user/link_telegram/ | User: student1
2025-06-21 15:22:42,431 INFO Request: GET /users/1352441813/ | User: student1
2025-06-21 15:22:45,284 INFO Request: GET /users/1352441813/ | User: student1
2025-06-21 15:22:49,550 INFO Request: GET /users/1352441813/ | User: student1
2025-06-21 15:22:57,470 INFO Request: POST /api/token/ | User: 
2025-06-21 15:22:57,545 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 15:23:00,222 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:23:06,656 INFO Request: GET /group/ | User: root
2025-06-21 15:23:14,471 INFO Request: POST /event/ | User: root
2025-06-21 15:23:14,487 WARNING Bad Request: /event/
2025-06-21 15:23:41,573 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:23:48,416 INFO Request: GET /group/ | User: root
2025-06-21 15:23:57,028 INFO Request: POST /event/ | User: root
2025-06-21 15:31:25,970 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:31:33,956 INFO Request: GET /group/ | User: root
2025-06-21 15:33:01,230 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:33:07,190 INFO Request: GET /group/ | User: root
2025-06-21 15:36:45,148 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:36:51,494 INFO Request: GET /group/ | User: root
2025-06-21 15:37:05,844 INFO Request: POST /event/ | User: root
2025-06-21 15:42:55,598 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:43:06,013 INFO Request: GET /group/ | User: root
2025-06-21 15:45:23,438 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:45:29,971 INFO Request: GET /group/ | User: root
2025-06-21 15:45:34,731 INFO Request: POST /event/ | User: root
2025-06-21 15:45:46,493 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:46:05,558 INFO Request: GET /group/ | User: root
2025-06-21 15:46:12,308 INFO Request: POST /event/ | User: root
2025-06-21 15:46:49,588 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:46:55,725 INFO Request: GET /group/ | User: root
2025-06-21 15:54:56,694 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:55:02,709 INFO Request: GET /group/ | User: root
2025-06-21 15:55:27,493 INFO Request: POST /event/ | User: root
2025-06-21 15:57:35,814 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:57:42,860 INFO Request: GET /group/ | User: root
2025-06-21 15:58:15,716 INFO Request: POST /api/token/ | User: 
2025-06-21 15:58:15,874 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 15:58:18,266 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:58:26,285 INFO Request: GET /group/ | User: root
2025-06-21 15:58:45,727 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 15:59:54,893 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:00:01,511 INFO Request: GET /group/ | User: root
2025-06-21 16:04:30,769 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:04:36,092 INFO Request: GET /group/ | User: root
2025-06-21 16:04:56,365 INFO Request: POST /event/ | User: root
2025-06-21 16:05:11,163 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:05:16,687 INFO Request: GET /group/ | User: root
2025-06-21 16:06:18,329 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:06:24,560 INFO Request: GET /group/ | User: root
2025-06-21 16:07:19,380 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:07:24,352 INFO Request: GET /group/ | User: root
2025-06-21 16:07:31,243 INFO Request: POST /event/ | User: root
2025-06-21 16:13:46,129 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:13:51,753 INFO Request: GET /group/ | User: root
2025-06-21 16:14:10,772 INFO Request: POST /event/ | User: root
2025-06-21 16:16:56,905 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:17:03,730 INFO Request: GET /group/ | User: root
2025-06-21 16:17:23,846 INFO Request: POST /event/ | User: root
2025-06-21 16:17:37,205 INFO Request: POST /api/token/ | User: 
2025-06-21 16:17:47,183 INFO Request: GET /event/ | User: root
2025-06-21 16:17:50,163 ERROR Internal Server Error: /event/27/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "D:\python\university_backend\event_api\views.py", line 149, in get_object
    return Event.objects.get(pk=self.kwargs['pk'])
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
event_api.models.Event.DoesNotExist: Event matching query does not exist.
2025-06-21 16:17:50,166 INFO Request: GET /event/27/ | User: root
2025-06-21 16:17:58,110 INFO Request: GET /event/26/ | User: root
2025-06-21 16:20:36,519 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:20:54,846 INFO Request: GET /group/ | User: root
2025-06-21 16:20:59,815 INFO Request: POST /event/ | User: root
2025-06-21 16:20:59,827 WARNING Bad Request: /event/
2025-06-21 16:32:58,285 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:33:03,742 INFO Request: GET /group/ | User: root
2025-06-21 16:33:32,609 INFO Request: POST /event/ | User: root
2025-06-21 16:34:09,513 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:34:40,212 INFO Request: GET /group/ | User: root
2025-06-21 16:35:40,917 INFO Request: POST /event/ | User: root
2025-06-21 16:35:56,485 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:36:09,288 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:36:52,026 INFO Request: GET /group/ | User: root
2025-06-21 16:38:04,962 INFO Request: POST /event/ | User: root
2025-06-21 16:38:27,304 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:38:50,157 INFO Request: GET /group/ | User: root
2025-06-21 16:40:13,216 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 16:40:37,210 INFO Request: GET /group/ | User: root
2025-06-21 16:40:43,632 INFO Request: POST /event/ | User: root
2025-06-21 16:41:16,162 INFO Request: GET /me/ | User: root
2025-06-21 16:41:19,765 INFO Request: GET /me/ | User: root
2025-06-21 16:48:29,643 INFO Request: GET /me/ | User: root
2025-06-21 16:55:37,681 INFO Request: POST /api/token/ | User: 
2025-06-21 16:55:46,003 INFO Request: GET /event/ | User: root
2025-06-21 16:59:59,278 INFO Request: POST /api/token/refresh/ | User: 
2025-06-21 16:59:59,348 INFO Request: GET /event/ | User: root
2025-06-21 17:08:25,845 INFO Request: GET /event/ | User: root
2025-06-21 17:11:08,845 INFO Request: GET /event/ | User: root
2025-06-21 17:13:06,392 INFO Request: GET /event/ | User: root
2025-06-21 17:14:28,989 INFO Request: GET /event/ | User: root
2025-06-21 17:15:02,063 INFO Request: GET /event/ | User: root
2025-06-21 17:17:50,304 INFO Request: GET /event/ | User: root
2025-06-21 17:18:10,358 INFO Request: GET /me/ | User: root
2025-06-21 17:18:12,420 INFO Request: GET /event/ | User: root
2025-06-21 17:18:21,696 INFO Request: POST /api/token/ | User: 
2025-06-21 17:18:21,758 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 17:29:04,148 INFO Request: POST /api/token/ | User: 
2025-06-21 17:29:04,320 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 17:29:06,983 INFO Request: GET /event/ | User: root
2025-06-21 17:29:09,862 INFO Request: GET /me/ | User: root
2025-06-21 17:29:16,423 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 17:29:19,559 INFO Request: GET /event/ | User: root
2025-06-21 17:32:45,548 INFO Request: POST /api/token/ | User: 
2025-06-21 17:32:45,737 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 17:32:48,211 INFO Request: GET /users/327525315/ | User: root
2025-06-21 17:32:57,497 INFO Request: GET /group/ | User: root
2025-06-21 17:33:05,095 INFO Request: POST /event/ | User: root
2025-06-21 17:33:10,039 INFO Request: GET /event/ | User: root
2025-06-21 19:00:10,440 INFO Request: POST /api/token/ | User: 
2025-06-21 19:00:10,601 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 19:00:19,398 INFO Request: GET /users/5409334956/ | User: root
2025-06-21 19:00:25,520 INFO Request: GET /me/ | User: root
2025-06-21 19:00:29,767 INFO Request: GET /event/ | User: root
2025-06-21 22:49:53,408 INFO Watching for file changes with StatReloader
2025-06-21 22:50:21,282 INFO Request: POST /api/token/ | User: 
2025-06-21 22:50:21,558 INFO Request: PATCH /user/link_telegram/ | User: student1
2025-06-21 22:50:23,627 INFO Request: GET /me/ | User: student1
2025-06-21 22:50:28,812 INFO Request: GET /users/1352441813/ | User: student1
2025-06-21 22:52:09,797 INFO Request: GET /event/ | User: student1
2025-06-21 22:52:47,785 INFO Request: POST /api/token/ | User: 
2025-06-21 22:52:47,862 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-21 22:52:49,997 INFO Request: GET /users/1352441813/ | User: root
2025-06-21 22:53:06,430 INFO Request: GET /group/ | User: root
2025-06-21 22:53:31,904 INFO Request: POST /event/ | User: root
2025-06-21 22:53:45,872 INFO Request: GET /event/ | User: root
2025-06-21 22:56:37,539 INFO Request: GET /me/ | User: root
2025-06-21 22:56:41,232 INFO Request: GET /event/ | User: root
2025-06-24 13:34:54,846 INFO Watching for file changes with StatReloader
2025-06-24 13:36:52,127 INFO Request: POST /api/token/ | User: 
2025-06-24 13:36:52,391 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-24 13:36:54,688 INFO Request: GET /event/ | User: root
2025-06-24 13:37:58,878 INFO Request: POST /api/token/ | User: 
2025-06-24 13:38:04,336 INFO Request: POST /api/token/ | User: 
2025-06-24 13:38:21,993 INFO Request: POST /event/ | User: root
2025-06-24 13:38:30,349 INFO Request: GET /event/ | User: 
2025-06-24 13:38:30,360 WARNING Unauthorized: /event/
2025-06-24 13:38:42,117 INFO Request: POST /event/ | User: root
2025-06-24 13:38:49,332 INFO Request: GET /event/ | User: root
2025-06-24 13:38:54,103 INFO Request: GET /event/ | User: root
2025-06-24 13:40:08,007 INFO Request: GET /me/ | User: root
2025-06-24 13:40:09,451 INFO Request: GET /event/ | User: root
2025-06-24 13:44:05,561 INFO Request: GET /event/ | User: root
2025-06-24 13:45:32,584 INFO Request: GET /event/ | User: root
2025-06-24 13:45:32,764 INFO Request: GET /media/photo/5404762823990565366_2Cj1SiN.jpg | User: 
2025-06-24 13:45:33,299 INFO Request: GET /media/photo/5404762823990565366.jpg | User: 
2025-06-24 13:46:43,456 INFO Request: GET /event/ | User: root
2025-06-24 13:46:43,606 INFO Request: GET /media/photo/5404762823990565366_2Cj1SiN.jpg | User: 
2025-06-24 13:47:33,635 INFO Request: GET /event/ | User: root
2025-06-24 13:47:33,927 INFO Request: GET /media/photo/5404762823990565366_2Cj1SiN.jpg | User: 
2025-06-24 13:48:30,636 INFO Request: POST /event/ | User: root
2025-06-24 13:48:34,401 INFO Request: GET /event/ | User: root
2025-06-24 13:48:56,509 INFO Request: GET / | User: root
2025-06-24 13:48:56,524 WARNING Not Found: /
2025-06-24 13:48:56,702 INFO Request: GET /favicon.ico | User: root
2025-06-24 13:48:56,717 WARNING Not Found: /favicon.ico
2025-06-24 13:48:59,842 INFO Request: GET /admin/ | User: root
2025-06-24 13:49:03,367 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-24 13:49:03,529 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-24 13:49:09,461 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-24 13:49:10,521 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366.jpg
2025-06-24 13:49:10,522 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371.jpg
2025-06-24 13:49:10,528 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38.webm
2025-06-24 13:49:10,531 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565366_2Cj1SiN.jpg
2025-06-24 13:49:10,532 INFO Deleted photo file: D:\python\university_backend\media\photo\5404762823990565371_uu5KGMx.jpg
2025-06-24 13:49:10,537 INFO Deleted video file: D:\python\university_backend\media\video\content_warning_0c895d38_6J3c4RA.webm
2025-06-24 13:49:10,546 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-24 13:49:10,705 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-24 13:49:10,895 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-24 13:49:16,175 INFO Request: GET /event/ | User: root
2025-06-24 13:49:44,216 INFO Request: GET /event/ | User: root
2025-06-24 13:49:50,208 INFO Request: POST /event/ | User: root
2025-06-24 13:49:52,827 INFO Request: GET /event/ | User: root
2025-06-24 13:49:52,874 INFO Request: GET /media/photo/5404762823990565366.jpg | User: 
2025-06-30 12:39:15,851 INFO Watching for file changes with StatReloader
2025-06-30 12:42:58,323 INFO Watching for file changes with StatReloader
2025-06-30 14:26:46,698 INFO Watching for file changes with StatReloader
2025-06-30 14:27:00,326 INFO Watching for file changes with StatReloader
2025-06-30 15:52:51,068 INFO Watching for file changes with StatReloader
2025-06-30 15:53:43,418 INFO Request: POST /api/token/ | User: 
2025-06-30 15:53:43,527 WARNING Unauthorized: /api/token/
2025-06-30 15:53:51,431 INFO Request: POST /api/token/ | User: 
2025-06-30 15:53:51,527 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-30 15:53:54,119 INFO Request: GET /event/ | User: root
2025-06-30 15:53:55,037 INFO Request: GET /me/ | User: root
2025-06-30 15:55:40,481 INFO Request: GET /me/ | User: root
2025-06-30 15:56:03,703 INFO Request: POST /api/token/ | User: 
2025-06-30 15:56:03,762 INFO Request: PATCH /user/link_telegram/ | User: root
2025-06-30 15:59:41,324 INFO Request: GET /users/5747889546/ | User: root
2025-06-30 16:00:05,281 INFO Request: GET /group/ | User: root
2025-06-30 16:00:28,666 INFO Request: GET /event/ | User: root
2025-06-30 16:00:42,880 INFO Request: GET /me/ | User: root
2025-06-30 16:50:53,007 INFO Request: POST /api/token/ | User: 
2025-06-30 16:51:20,286 INFO Request: POST /event/ | User: root
2025-06-30 16:51:20,304 WARNING Bad Request: /event/
2025-06-30 16:51:35,535 INFO Request: GET /group/ | User: root
2025-06-30 16:51:39,698 INFO Request: POST /group/ | User: root
2025-06-30 16:52:00,460 INFO Request: POST /group/ | User: root
2025-06-30 16:52:03,624 INFO Request: POST /event/ | User: root
2025-06-30 16:52:12,057 INFO Request: POST /event/ | User: root
2025-06-30 16:52:15,182 INFO Request: GET /event/ | User: root
2025-06-30 16:52:56,202 INFO Request: GET /event/ | User: root
2025-06-30 16:53:15,952 INFO Request: GET /event/1/ | User: root
2025-06-30 16:53:40,285 INFO Watching for file changes with StatReloader
2025-06-30 16:53:46,049 INFO Request: GET / | User: 
2025-06-30 16:53:46,073 WARNING Not Found: /
2025-06-30 16:53:46,208 INFO Request: GET /favicon.ico | User: 
2025-06-30 16:53:46,219 WARNING Not Found: /favicon.ico
2025-06-30 16:53:46,666 INFO Request: GET /admin/ | User: 
2025-06-30 16:53:46,777 INFO Request: GET /admin/login/ | User: 
2025-06-30 16:53:49,536 INFO Request: POST /admin/login/ | User: root
2025-06-30 16:53:49,698 INFO Request: GET /admin/ | User: root
2025-06-30 16:53:52,494 INFO Request: GET /admin/event_api/eventphoto/ | User: root
2025-06-30 16:53:52,609 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-30 16:53:53,767 INFO Request: GET /admin/ | User: root
2025-06-30 16:54:37,666 INFO Watching for file changes with StatReloader
2025-06-30 16:54:40,187 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-30 16:54:40,291 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-30 16:54:41,567 INFO Request: GET /admin/event_api/event/2/change/ | User: root
2025-06-30 16:54:41,662 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-30 16:54:43,947 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-30 16:54:48,392 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-30 16:54:49,377 INFO Request: POST /admin/event_api/event/ | User: root
2025-06-30 16:54:49,631 INFO Request: GET /admin/event_api/event/ | User: root
2025-06-30 16:54:49,721 INFO Request: GET /admin/jsi18n/ | User: root
2025-06-30 16:55:15,443 INFO Request: POST /event/1/ | User: root
2025-06-30 16:55:15,455 WARNING Method Not Allowed: /event/1/
2025-06-30 16:55:17,707 INFO Request: POST /event/ | User: root
2025-06-30 16:55:37,127 INFO Request: GET /event/3/ | User: root
2025-06-30 16:56:25,971 INFO Request: POST /api/token/ | User: 
2025-06-30 16:56:35,459 INFO Request: GET /event/ | User: root
2025-06-30 16:57:24,650 INFO Request: GET /event/ | User: root
2025-06-30 16:57:27,843 INFO Request: POST /event/ | User: root
2025-06-30 16:57:27,852 WARNING Bad Request: /event/
2025-06-30 16:57:39,314 INFO Request: POST /event/ | User: root
2025-06-30 16:57:49,981 INFO Request: GET /event/1. | User: 
2025-06-30 16:57:50,004 WARNING Not Found: /event/1.
2025-06-30 16:57:57,673 INFO Request: GET /event/4 | User: 
2025-06-30 16:57:57,753 INFO Request: GET /event/4/ | User: root
2025-06-30 16:57:59,206 INFO Request: GET /event/4/ | User: root
2025-06-30 16:58:05,727 INFO Request: GET /event/ | User: root
2025-06-30 16:58:16,138 INFO Request: DELETE /event/3/ | User: root
2025-06-30 16:58:23,803 INFO Request: POST /event/ | User: root
2025-06-30 16:58:25,937 INFO Request: GET /event/ | User: root
2025-06-30 16:59:01,515 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 16:59:02,239 INFO Watching for file changes with StatReloader
2025-06-30 17:02:05,724 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:02:06,384 INFO Watching for file changes with StatReloader
2025-06-30 17:06:45,276 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-30 17:06:45,947 INFO Watching for file changes with StatReloader
2025-06-30 17:06:46,733 INFO Request: GET /admin/ | User: root
2025-06-30 17:06:48,540 INFO Request: GET /photos | User: root
2025-06-30 17:06:48,623 ERROR Internal Server Error: /photos/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\python\university_backend\event_api\views.py", line 166, in get
    queryset = EventPhoto.objects.all().selected_related('event')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'selected_related'. Did you mean: 'select_related'?
2025-06-30 17:06:48,626 INFO Request: GET /photos/ | User: 
2025-06-30 17:06:56,933 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:06:57,580 INFO Watching for file changes with StatReloader
2025-06-30 17:06:58,349 ERROR Internal Server Error: /photos/
Traceback (most recent call last):
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\python\university_backend\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\university_backend\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'rest_framework.utils.serializer_helpers.ReturnList'>`
2025-06-30 17:06:58,350 INFO Request: GET /photos/ | User: 
2025-06-30 17:07:13,604 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:07:14,355 INFO Watching for file changes with StatReloader
2025-06-30 17:07:17,193 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:07:17,817 INFO Watching for file changes with StatReloader
2025-06-30 17:07:18,663 INFO Request: GET /photos/ | User: 
2025-06-30 17:07:34,893 INFO D:\python\university_backend\event_api\serializers.py changed, reloading.
2025-06-30 17:07:35,505 INFO Watching for file changes with StatReloader
2025-06-30 17:07:36,252 INFO Request: GET /photos/ | User: 
2025-06-30 17:07:48,039 INFO Request: GET /__debug__/render_panel/ | User: root
2025-06-30 17:07:54,534 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:07:55,157 INFO Watching for file changes with StatReloader
2025-06-30 17:07:56,020 INFO Request: GET /photos/ | User: 
2025-06-30 17:07:57,367 INFO Request: GET /__debug__/render_panel/ | User: root
2025-06-30 17:07:59,831 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:08:00,494 INFO Watching for file changes with StatReloader
2025-06-30 17:08:01,282 INFO Request: GET /photos/ | User: 
2025-06-30 17:08:08,283 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:08:08,938 INFO Watching for file changes with StatReloader
2025-06-30 17:08:16,752 INFO D:\python\university_backend\event_api\views.py changed, reloading.
2025-06-30 17:08:17,387 INFO Watching for file changes with StatReloader
2025-06-30 17:08:18,153 INFO Request: GET /photos/ | User: 
2025-06-30 17:08:18,205 WARNING Unauthorized: /photos/
2025-06-30 17:09:33,988 INFO Watching for file changes with StatReloader
2025-06-30 17:09:36,046 INFO Request: GET /photos/ | User: root
